### ISSUE TITLE
PinUtils variable not created on pinit.js exec

### ISSUE THREAD

**Issue by vatavale** [pinterest/widgets#60] opened 2015-12-05 11:17 UTC
In [official cookbook](https://developers.pinterest.com/docs/widgets/pin-it/) of Pinterest I read:

    Including pinit.js gives you a global variable, PinUtils.
    PinUtils.pinOne() -- This function opens the Pin Create form [...] to saving an image you have chosen from your site.

I tried to call this function from docs:
```javascript
PinUtils.pinOne({ 'media': 'http://example.com/image.jpg' })
```
But seems like there was no PinUtils variable created on pinit.js execution.
Please, take a look at [jsFeedle](http://jsfiddle.net/vatavale/8tvf4snn/1/).

**Comment by fletc3her** [comment] 2016-01-26 04:56
FWIW, the problem is that the version of pinit_main.js in this repository is far out of date. If you get the current version from http://assets.pinterest.com/js/pinit_main.js you will see the `pinOne` function and other new features and bug fixes.

**Comment by kentbrew** [comment] 2016-02-22 22:09
Sorry about that; getting ready to update now.

**Comment by kentbrew** [comment] 2016-02-22 22:58
Closing for rewrite.

**Closed by kentbrew** 2016-02-22 22:58 UTC
